### ISSUE TITLE
Automated toolchain install.

### ISSUE THREAD

**Issue by jklmnn** [jklmnn/continuous-verification#2]
The current hack of piping the output of `yes` into `doinstall` isn't the way to go. Provide a better way to automatically install the GNAT and SPARK toolchain.

**Comment by reznikmm** [comment]
Gnat community 2018 has completely different installer. AdaCore provides installation script here:

https://github.com/AdaCore/gnat_community_install_script

**Comment by jklmnn** [comment]
I already forgot about this issue. For another project I built a fork of your [GNAT Docker container](https://github.com/jklmnn/docker-gnat/tree/gpl.2018.spark) that also installs SPARK 2018. I should update this repo to use this.

**Comment by jklmnn** [comment]
I have adapted the gnat community install script for the current version.
